apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kooobernettes
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kooobernettes
